name: flutter_myalgo_connect
description: A Flutter web plugin to approve or deny Algorand transactions using MyAlgo Connect.
version: 1.0.0
homepage: https://www.algorand.com
repository: https://github.com/RootSoft/flutter-myalgo-connect
issue_tracker: https://github.com/RootSoft/flutter-myalgo-connect/issues

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  js: ^0.6.3
  plugin_platform_interface: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Testing framework
  test: ^1.16.8

  # Linter
  pedantic: ^1.11.0

flutter:
  plugin:
    platforms:
      web:
        pluginClass: MyAlgoPlugin
        fileName: myalgo_connect_web.dart
